server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       default-zone: http://localhost:8761/eureka
       
#serverºØ»∫≈‰÷√
#spring:
#  application:
#    name: eureka
#
#---
#spring:
#  profiles: eureka1
#eureka:
#  instance:
#    hostname: eureka1
#  client:
#    service-url:
#      default-zone: http://localhost:8762/eureka,http://localhost:8763/eureka
#---
#spring:
#  profiles: eureka2
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka,http://localhost:8763/eureka
#---
#spring:
#  profiles: eureka3
#eureka:
#  instance:
#    hostname: eureka3
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka,http://localhost:8762/eureka
